### ISSUE TITLE
Game crashes regularly (Charm mod incompatibility)

### ISSUE THREAD

**Issue by gbpeet** [filloax/ruins-of-growsseth#4]
With Ruins-of-Growseth installed Minecraft crashes pretty quickly after starting (about 5-15 minutes). I uninstalled the mod and it stopped crashing. Most likely interference from other mods. Attached are crash reports.
[crash-2024-11-23_11.33.25-server.txt](https://github.com/user-attachments/files/17882597/crash-2024-11-23_11.33.25-server.txt)
[crash-2024-11-23_11.27.27-server.txt](https://github.com/user-attachments/files/17882598/crash-2024-11-23_11.27.27-server.txt)
[crash-2024-11-23_10.56.04-server.txt](https://github.com/user-attachments/files/17882599/crash-2024-11-23_10.56.04-server.txt)
[crash-2024-11-23_10.53.50-server.txt](https://github.com/user-attachments/files/17882600/crash-2024-11-23_10.53.50-server.txt)
[crash-2024-11-23_07.21.55-server.txt](https://github.com/user-attachments/files/17882601/crash-2024-11-23_07.21.55-server.txt)

**Comment by costentz** [comment]
Looks like the game crashes when a mooblom from the Charm mod tries to place flowers.
I just pushed a quick fix and built a test version, can you [try it](https://github.com/filloax/ruins-of-growsseth/releases/tag/nightly-release-1.21) and tell us if it works?
(ignore the closed as completed message, I misclicked)

**Comment by gbpeet** [comment]
The game is no longer crashing. The fix seems to have worked. Thank you!


Sent from Yahoo Mail for iPhone


On Saturday, November 23, 2024, 4:06 PM, costantino2000 ***@***.***> wrote:




Looks like the game crashes when a mooblom from the Charm mod tries to place flowers.
I pushed a quick fix and built a test version, can you try it and tell us if it works?

**Comment by costentz** [comment]
Glad to hear it! We'll publish a stable version with the fix then, let us know if there are any other problems.
